// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojbdiawbfqyepbadnivw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qYmRpYXdiZnF5ZXBiYWRuaXZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NTE3MDMsImV4cCI6MjA2OTEyNzcwM30.i-Kqf-JpU9pmEdcVXF634D8N1FD-UuHh99A_evsmLuc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});